apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-persistence-profile
  namespace: avi-feature
  labels:
    feature: persistence-profile 
spec:
  replicas: 2
  selector:
    matchLabels:
      feature: persistence-profile       
  template:
    metadata:
      labels:
        feature: persistence-profile 
    spec:
      containers:
      - name: nginx-persistence-profile 
        image: nginx:stable-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx
          mountPath: /etc/nginx
          readOnly: true
      volumes:
      - name: nginx
        configMap:
          name: nginx
