apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-lb-algorithm
  namespace: avi-feature
  labels:
    feature: lb-algorithm 
spec:
  replicas: 2
  selector:
    matchLabels:
      feature: lb-algorithm       
  template:
    metadata:
      labels:
        feature: lb-algorithm 
    spec:
      containers:
      - name: nginx-lb-algorithm 
        image: nginx:stable-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx
          mountPath: /etc/nginx
          readOnly: true
      volumes:
      - name: nginx
        configMap:
          name: nginx
