apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ratio-a-services
  namespace: avi-feature
  labels:
    feature: ratio-a-services 
spec:
  replicas: 2
  selector:
    matchLabels:
      feature: ratio-a-services       
  template:
    metadata:
      labels:
        feature: ratio-a-services 
    spec:
      containers:
      - name: nginx-ratio-a-services 
        image: nginx:stable-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx
          mountPath: /etc/nginx
          readOnly: true
      volumes:
      - name: nginx
        configMap:
          name: nginx
