apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ratio-b-services
  namespace: avi-feature
  labels:
    feature: ratio-b-services 
spec:
  replicas: 2
  selector:
    matchLabels:
      feature: ratio-b-services       
  template:
    metadata:
      labels:
        feature: ratio-b-services 
    spec:
      containers:
      - name: nginx-ratio-b-services 
        image: nginx:stable-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: nginx
          mountPath: /etc/nginx
          readOnly: true
        - mountPath: /etc/nginx/ssl
          name: nginx-ssl
      volumes:
      - name: nginx
        configMap:
          name: nginx
      - name: nginx-ssl
        secret:
          secretName: nginx-ssl
