apiVersion: v1
kind: Service
metadata:
  name: nginx-ratio-a-services
  namespace: avi-feature
  labels:
    feature: ratio-a-services 
  annotations:
    avi_proxy: '{"virtualservice": {"east_west_placement": false}, "poolgroup": {"members": [{"ratio": 10, "pool_ref": "/api/pool/?name=nginx-ratio-a-services-pool-80-tcp"}, {"ratio": 1, "pool_ref": "/api/pool/?name=nginx-ratio-b-services-pool-80-tcp"}]}}'
    #avi_proxy: '{"virtualservice": {"east_west_placement": false}}'
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: tcp
  selector:
    feature: ratio-a-services
  type: LoadBalancer

