apiVersion: v1
kind: Service
metadata:
  name: nginx-ratio-a-services
  namespace: avi-feature
  labels:
    feature: ratio-a-services 
  annotations:
    avi_proxy: |
      {"virtualservice": {
        "enable_rhi": true,
        "east_west_placement": false
        }
      }
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: tcp
  selector:
    feature: ratio-a-services
  type: LoadBalancer

