apiVersion: v1
kind: Service
metadata:
  name: nginx-ratio-b-services
  namespace: avi-feature
  labels:
    feature: ratio-b-services 
  annotations: 
    proxy_listener: "no"
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: tcp
  selector:
    feature: ratio-b-services
  type: LoadBalancer
