apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-http-redirect-by-service
  namespace: avi-feature
  labels:
    feature: http-redirect-by-service 
spec:
  replicas: 2
  selector:
    matchLabels:
      feature: http-redirect-by-service       
  template:
    metadata:
      labels:
        feature: http-redirect-by-service 
    spec:
      containers:
      - name: nginx-http-redirect-by-service 
        image: nginx:stable-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: nginx
          mountPath: /etc/nginx
          readOnly: true
        - mountPath: /etc/nginx/ssl
          name: nginx-ssl
      volumes:
      - name: nginx
        configMap:
          name: nginx
      - name: nginx-ssl
        secret:
          secretName: nginx-ssl
