apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-disable-vs-creation
  namespace: avi-feature
  labels:
    feature: disable-vs-creation 
spec:
  replicas: 2
  selector:
    matchLabels:
      feature: disable-vs-creation       
  template:
    metadata:
      labels:
        feature: disable-vs-creation 
    spec:
      containers:
      - name: nginx-disable-vs-creation 
        image: nginx:stable-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx
          mountPath: /etc/nginx
          readOnly: true
      volumes:
      - name: nginx
        configMap:
          name: nginx
