apiVersion: v1
kind: Service
metadata:
  name: nginx-disable-vs-creation
  namespace: avi-feature
  labels:
    feature: disable-vs-creation
  annotations:
    proxy_listener: "no"
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: tcp
  selector:
    feature: disable-vs-creation
  type: LoadBalancer
